Experiment:
    exp_id: PatchTST/nzdusd_pto
    prev_exp_id: PatchTST/nzdusd_predict
Hardware:
    random_seed: 2021
    num_workers: 2
    gpu: 0
    use_multi_gpu: false
    gpus: null
Dataset:
    root_path: ../dataset
    data_path: exchange_rate_600s.csv
    task_type: U
    univariate: nzdusd
    date_col: transact_time
    n_vars: 1
    seq_len: 440
    label_len: 0
    pred_len: 88
    interval: 1
    standardize: true
    enc_freq: null
Model:
    model: PatchTST
    decomp: false
    decomp_ksize: null
    revin: true
    revin_affine: false
    revin_subtract_last: false
    patch_len: 12
    patch_stride: 6
    patch_padding: end
    pos_enc: learned
    e_layers: 3
    d_model: 16
    n_heads: 4
    d_ff: 128
    activation: gelu
    dropout: 0.3
    shared_proj: true
Allocate:
    uncertainty_quantile: 1
    batch_size: 32
    load_prev_weights: true