Experiment:
    exp_id: TimesNet/usdcny_pto
    prev_exp_id: TimesNet/usdcny_predict
Hardware:
    random_seed: 2021
    num_workers: 2
    gpu: 0
    use_multi_gpu: false
    gpus: null
Dataset:
    root_path: ../dataset
    data_path: exchange_rate_600s.csv
    task_type: U
    univariate: usdcny
    date_col: transact_time
    n_vars: 1
    seq_len: 440
    label_len: 0
    pred_len: 88
    interval: 1
    standardize: true
    enc_freq: null
Model:
    model: TimesNet
    pos_enc: sincos
    temp_enc: none
    revin: true
    revin_affine: false
    revin_subtract_last: false
    topk: 5
    e_layers: 2
    d_model: 16
    d_ff: 32
    num_kernels: 6
    activation: gelu
    dropout: 0.1
Allocate:
    uncertainty_quantile: 0.1
    batch_size: 32
    load_prev_weights: true