Experiment:
    exp_id: FEDformer/usdcny_pto
    prev_exp_id: FEDformer/usdcny_predict
Hardware:
    random_seed: 2021
    num_workers: 2
    gpu: 0
    use_multi_gpu: false
    gpus: null
Dataset:
    root_path: ../dataset
    data_path: exchange_rate_600s.csv
    task_type: U
    univariate: usdcny
    date_col: transact_time
    n_vars: 1
    seq_len: 440
    label_len: 0
    pred_len: 88
    interval: 1
    standardize: true
    enc_freq: null
Model:
    model: FEDformer
    pos_enc: none
    temp_enc: none
    e_layers: 2
    d_layers: 1
    d_model: 512
    n_heads: 8
    n_modes: 64
    d_ff: 2048
    decomp_ksizes: 
    - 24
    activation: gelu
    dropout: 0.05
Allocate:
    uncertainty_quantile: 0.8
    batch_size: 32
    load_prev_weights: true