Experiment:
    exp_id: DLinear/usdcny_pto
    prev_exp_id: DLinear/usdcny_predict
Hardware:
    random_seed: 2021
    num_workers: 2
    gpu: 0
    use_multi_gpu: false
    gpus: null
Dataset:
    root_path: ../dataset
    data_path: exchange_rate_600s.csv
    task_type: U
    univariate: usdcny
    date_col: transact_time
    n_vars: 1
    seq_len: 440
    label_len: 0
    pred_len: 88
    interval: 1
    standardize: true
    enc_freq: null
Model:
    model: DLinear
    decomp_ksize: 25
    shared_proj: true
Allocate:
    uncertainty_quantile: 0.8
    batch_size: 32
    load_prev_weights: true